### ISSUE TITLE
`notify` can be nil when called from `vscode`

### ISSUE THREAD

**Issue by PromethiumL** [kiyoon/python-import.nvim#2]
First of all, thank you for the nice plugin! It works nicely.

Using the default lazy config, `<M-CR>` can import the module correctly, but it failed to send a notification via `notify`.
Error says 'vscode.notify' at line 10 of `lua/python_import/notify.lua`.

I fixed the problem by using a more strict the condition at line 3, but not sure if that's the supposed way to fix it.
```diff
M = {}

local status2, vscode = pcall(require, "vscode")
- if status2 then
+ if status2 and vscode.notify ~= nil then
  ---@param message string|string[]
  M.notify = function(message, level, opts)
    if type(message) == "table" then
      message = table.concat(message, "\n")
    end
    vscode.notify(message, level)
  end
else
  local status, nvim_notify = pcall(require, "notify")
  if status then
    M.notify = nvim_notify
  end
end
```

**Comment by kiyoon** [comment]
Hi! Thanks for reporting the issue. Are you using vscode and vscode-neovim plugin? In my settings, when it can import the vscode plugin, it can also use the notify feature.

**Comment by kiyoon** [comment]
Thank you! I fixed as you've suggested so I hope you don't face the issue anymore.

**Comment by PromethiumL** [comment]
> Hi! Thanks for reporting the issue. Are you using vscode and vscode-neovim plugin? In my settings, when it can import the vscode plugin, it can also use the notify feature.

No. I'm using the `vscode` [theme](https://github.com/Mofiqul/vscode.nvim) instead, on nvim. They happen to have the same package name. 😄

**Comment by kiyoon** [comment]
oh haha well their namespace collides with vscode-neovim.. well I guess I can still fix it like how you did it!
