### ISSUE TITLE
Extremely slow on large codebase

### ISSUE THREAD

**Issue by Diaoul** [kiyoon/python-import.nvim#4]
Thanks for the plugin 🙏 I cannot find a way for `pyright` to actually auto import stuff from my project, it works well for builtin (e.g. datetime) or dependencies (e.g. sqlalchemy) but not the project itself sadly with the exception of some modules that have already been traversed it seems.

I understood this was one of the limitations of pyright. Adding this bit of information because it maybe the reason of the slowness?

**Describe the bug**
I'm running this on a fairly large codebase, it takes 10+ seconds to resolve an import

**To Reproduce**
Run on a large codebase

**Expected behavior**
It's fast (subsecond)

**Output of `:checkhealth python_import`**

```
python-import ~
- OK Using Neovim >= 0.10.0
- OK `rg` is installed
- OK `fd` is installed
- OK `python-import` is installed
- ERROR python-import cli (0.1.0) and nvim plugin version (0.1.0+13.gd083764) mismatch.
```

**Output of `nvim --version`**

```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

**Comment by kiyoon** [comment]
I don't know where exactly the slowness comes from, but I assume it may be the treesitter search.

It first find the entire list of files with the search results using `fd` and `rg`. Can you check how long this takes?

```bash
fd -e py -x rg --word-regexp --fixed-strings --json import_module_name
```
(brought from https://github.com/kiyoon/python-import.nvim/blob/d083764d679e791026610faf5340f38ee5f5507c/src/python_import/utils.py#L256-L261)

Assuming that the search result is still massive, finding the module with `py-tree-sitter` may take some time too, because it has to look up the syntax of many files. Basically, running this function on many files may take time. You can also benchmark this. (with many files, like all search results from above)

https://github.com/kiyoon/python-import.nvim/blob/d083764d679e791026610faf5340f38ee5f5507c/src/python_import/utils.py#L87-L92


Once we know the benchmark of each piece, we can maybe come up with a solution.

**Comment by Diaoul** [comment]
> ```fd -e py -x rg --word-regexp --fixed-strings --json import_module_name```

14s

This seems to be what takes the most time, the rest is 4s long (or less)

**Comment by kiyoon** [comment]
what happens if you do this: `rg --word-regexp --fixed-strings --json --type python import_module_name`

Maybe rg optimises it better if we use the `--type` option rather than `fd`

**Comment by Diaoul** [comment]
Much faster: ~1s

**Comment by kiyoon** [comment]
Very good to know. It will still take some seconds but I'll fix this first then! Thanks for letting me know.

**Comment by kiyoon** [comment]
I hope with this update you can have a better experience. Let me know if something goes wrong.

Also, from your health result, it appears that you installed the CLI version from pypi (maybe) and it does not match the latest plugin version. Make sure that you configure your plugin manager to automatically install the package again as you update the plugin.

**Comment by Diaoul** [comment]
Indeed 👍 
There are 2 lines in the configuration example and one is commented out. Which one should I choose and based on what?

```lua
    -- build = "pipx install . --force",
    build = "uv tool install . --force --reinstall",
```

**Comment by kiyoon** [comment]
They are basically two identical tools. [Pipx](https://github.com/pypa/pipx) is the standard made by pypa written in python. [uv](https://github.com/astral-sh/uv) is written in rust and has incredible speed. I personally like what uv offers, which makes the installation instant.

Whatever you use, they will simple install the CLI in an separate virtual environment and link the executable to `~/.local/bin/python-import` which should be in your `$PATH`.

Note that you can even use `pip` to install it. It just won't make a virtual environment for you.

**Comment by Diaoul** [comment]
Thanks for the answer, much clearer what is required for the plugin to work.
I knew those tools but I was not sure how to use them in the context of a neovim plugin.

I do have other nvim plugins installed that use python under the hood (e.g. neotest, debugpy) but for which I never had to do this build step 🤔 Maybe there is a way to simplify 🤷

**Comment by kiyoon** [comment]
I think neotest have simple requirements in their project. It just requires pytest to be installed in your environment.  
It's the same for debugpy. It requires you to install debugpy yourself. Given that these tools are pretty stable, you don't really need to update them frequently either.

But in my case,
- I have external dependencies that I need to pull from pip, like py-tree-sitter.
- The dependencies will change over development
- I don't want people to install my plugin in all of their environments. One tool is enough for all projects. Also, installing the wrong version is a source of error.

Thus I decided to make my python CLI program. All can be rewritten in Lua, to be fair, but development-wise python is easier for me.
